apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secrets
type: Opaque
data:
  DATABASE_PW: {{.Values.dbPw | b64enc }}
  ADMIN_PW:  {{.Values.dbPw | b64enc}}
  DATABASE_URL: {{ print "postgres://postgres:" .Values.dbPw "@" .Values.name "-postgres-service:5432/django_db" | b64enc}}